#!/bin/bash

#update machine code from git

rm -r /home/boys/programFiles/camden-robotics/src/edu/.team3329/*
cp -r /home/boys/programFiles/camden-robotics/src/edu/team3329/* /home/boys/programFiles/camden-robotics/src/edu/.team3329

